# SPDX-FileCopyrightText: 2023 Comcast Cable Communications Management, LLC
# SPDX-License-Identifier: Apache-2.0

websocket:
  url_path: api/v2/device
  back_up_url: 
xmidt_credentials:
  url: "JWT Issuer"
  file_name: outputJwt.txt
  file_permissions: 0777
  http_client:
    tls:
      insecure_skip_verify: true
      certificates: 
        - certificate_file: certs/cert.pem
          key_file:         certs/key.pem
      min_version: 771 # 0x0303, the TLS 1.2 version uint16
identity:
  device_id: mac:4ca161000109
  serial_number: 1800deadbeef
  hardware_model: fooModel
  hardware_manufacturer: barManufacturer
  firmware_version: v0.0.1
  partner_id: foobar
xmidt_service:
    backoff:
        max_delay: 600s
        min_delay: 7s
    jwt_txt_redirector:
        allowed_algorithms: ["RS256"]
        pems:
        - |
          -----BEGIN PUBLIC KEY-----
          -----END PUBLIC KEY-----
        timeout: 10s
    url: "websocket or redirect server"
operational_state:
  last_reboot_reason: sleepy
  boot_time: "2024-02-28T01:04:27Z"
storage:
  temporary: ~/local-rdk-testing/temporary
  durable: ~/local-rdk-testing/durable
mock_tr_181:
  enabled: true
  file_path: /mock_tr181.json
