---
linters-settings:
  misspell:
    locale: US
  errorlint:
    # Report non-wrapping error creation using fmt.Errorf
    errorf: false

linters:
  enable:
    - bodyclose
    - dupl
    - errorlint
    - goconst
    - gosec
    - misspell
    - unconvert
    - prealloc
  disable:
    - errcheck
    - ineffassign

issues:
  exclude-rules:
    - path: _test.go
      linters:
        - dupl
        - funlen
    - path: internal/credentials/cmd/example/main.go
      linters:
        - gosec
    - path: internal/nhooyr.io
      linters:
        - bodyclose
        - errorlint
        - gosec
        - goconst
        - misspell
        - prealloc

run:
  skip-files:
    - "internal/jwtxt/keypairs_for_test.go"